export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const INSERT_CUSTOMER = 'INSERT_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
